---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: ro:namespaces
rules:
- apiGroups:
  - '*'
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: rw:events
rules:
- apiGroups:
  - '*'
  resources:
  - events
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: rw:cloud-resources
rules:
- apiGroups:
  - cloud.appvia.io
  resources:
  - "*"
  verbs:
  - "*"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kube-cloud:sa:ro:namespaces
roleRef:
  kind: ClusterRole
  name: ro:namespaces
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: kube-cloud
  namespace: kube-cloud
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kube-cloud:sa:rw:events
roleRef:
  kind: ClusterRole
  name: rw:events
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: kube-cloud
  namespace: kube-cloud
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kube-cloud:sa:ro:cloudresources
roleRef:
  kind: ClusterRole
  name: rw:cloud-resources
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: cloud-resources
  namespace: kube-cloud
---
