/*
Copyright 2018 All rights reserved - Appvia.io

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by lister-gen

package v1

import (
	v1 "github.com/gambol99/resources/pkg/apis/resources/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// CloudTemplateLister helps list CloudTemplates.
type CloudTemplateLister interface {
	// List lists all CloudTemplates in the indexer.
	List(selector labels.Selector) (ret []*v1.CloudTemplate, err error)
	// Get retrieves the CloudTemplate from the index for a given name.
	Get(name string) (*v1.CloudTemplate, error)
	CloudTemplateListerExpansion
}

// cloudTemplateLister implements the CloudTemplateLister interface.
type cloudTemplateLister struct {
	indexer cache.Indexer
}

// NewCloudTemplateLister returns a new CloudTemplateLister.
func NewCloudTemplateLister(indexer cache.Indexer) CloudTemplateLister {
	return &cloudTemplateLister{indexer: indexer}
}

// List lists all CloudTemplates in the indexer.
func (s *cloudTemplateLister) List(selector labels.Selector) (ret []*v1.CloudTemplate, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.CloudTemplate))
	})
	return ret, err
}

// Get retrieves the CloudTemplate from the index for a given name.
func (s *cloudTemplateLister) Get(name string) (*v1.CloudTemplate, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("cloudtemplate"), name)
	}
	return obj.(*v1.CloudTemplate), nil
}
