/*
Copyright 2018 All rights reserved - Appvia.io

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by lister-gen

package v1

// CloudResourceListerExpansion allows custom methods to be added to
// CloudResourceLister.
type CloudResourceListerExpansion interface{}

// CloudResourceNamespaceListerExpansion allows custom methods to be added to
// CloudResourceNamespaceLister.
type CloudResourceNamespaceListerExpansion interface{}

// CloudStatusListerExpansion allows custom methods to be added to
// CloudStatusLister.
type CloudStatusListerExpansion interface{}

// CloudStatusNamespaceListerExpansion allows custom methods to be added to
// CloudStatusNamespaceLister.
type CloudStatusNamespaceListerExpansion interface{}

// CloudTemplateListerExpansion allows custom methods to be added to
// CloudTemplateLister.
type CloudTemplateListerExpansion interface{}
