/*
Copyright 2018 All rights reserved - Appvia.io

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package v1

import (
	time "time"

	resources_v1 "github.com/gambol99/resources/pkg/apis/resources/v1"
	versioned "github.com/gambol99/resources/pkg/client/clientset/versioned"
	internalinterfaces "github.com/gambol99/resources/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/gambol99/resources/pkg/client/listers/resources/v1"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CloudResourceInformer provides access to a shared informer and lister for
// CloudResources.
type CloudResourceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.CloudResourceLister
}

type cloudResourceInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewCloudResourceInformer constructs a new informer for CloudResource type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCloudResourceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCloudResourceInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredCloudResourceInformer constructs a new informer for CloudResource type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCloudResourceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options meta_v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CloudV1().CloudResources(namespace).List(options)
			},
			WatchFunc: func(options meta_v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CloudV1().CloudResources(namespace).Watch(options)
			},
		},
		&resources_v1.CloudResource{},
		resyncPeriod,
		indexers,
	)
}

func (f *cloudResourceInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCloudResourceInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *cloudResourceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&resources_v1.CloudResource{}, f.defaultInformer)
}

func (f *cloudResourceInformer) Lister() v1.CloudResourceLister {
	return v1.NewCloudResourceLister(f.Informer().GetIndexer())
}
